version: '3.1'

services:

  api:
      stdin_open: true
      tty: true
      restart: always
      build: ./app
      volumes:
        - ./conf:/root/conf
      ports:
        - "5003:5003"
      command: ['python3.6', 'root/serverAPI.py']

